# Generated by Django 5.2 on 2025-04-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerauthtokens',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerauthtokens',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
